table dim_sensor_cleaned
	lineageTag: 64e34e03-683e-441f-a021-7e8cb6292305

	column SensorID
		dataType: string
		lineageTag: 67939e47-f6c8-4f3c-8ea1-806427583f7a
		summarizeBy: none
		sourceColumn: SensorID

		annotation SummarizationSetBy = Automatic

	column SensorType
		dataType: string
		lineageTag: 21264e13-e246-4ca6-8374-b1b3706b918a
		summarizeBy: none
		sourceColumn: SensorType

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 84faed71-09a0-402c-9e2e-26cf226f6d49
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column CalibrationDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b4614313-e8e2-40b7-81e1-85eabd5878af
		summarizeBy: none
		sourceColumn: CalibrationDate

		variation Variation
			isDefault
			relationship: 2b7c7d6a-d90f-4eb1-9470-d6d26c405ea3
			defaultHierarchy: LocalDateTable_d150c8ea-6d94-41e1-ad37-0a45febfcf27.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_sensor_cleaned = m
		mode: import
		source =
				let
<<<<<<< HEAD
				    Source = Csv.Document(File.Contents("D:\JUNIOR USIU\Summer 2025\Data Viz\Final project\powerbi-capstone-Automotive-parts-02\Data\cleaned\dim_sensor_cleaned.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
=======
				    Source = Csv.Document(File.Contents("C:\Users\jkaru\VSCODE PYTHON PROJECTS\powerbi-capstone-Automotive-parts-02\Data\cleaned\dim_sensor_cleaned.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
>>>>>>> 765dc9742845f51fc65c90ebfd4c90aa0d80c1aa
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CalibrationDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

