table dim_equipment_cleaned
	lineageTag: 91217463-8038-42a9-9e24-a8089538f615

	column EquipmentID
		dataType: string
		lineageTag: de4a73b2-ecbd-4796-bc52-a74c423e28b2
		summarizeBy: none
		sourceColumn: EquipmentID

		annotation SummarizationSetBy = Automatic

	column EquipmentType
		dataType: string
		lineageTag: 16409b37-f651-4ca0-b6a1-6979daaeefbf
		summarizeBy: none
		sourceColumn: EquipmentType

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		lineageTag: cf11e3a9-df88-47ea-a83f-0b4c262f4cb4
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	column InstallationDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 774136bf-35c3-4e70-a09d-00e4c0bd9ebb
		summarizeBy: none
		sourceColumn: InstallationDate

		variation Variation
			isDefault
			relationship: 984917ec-1474-4a49-9e02-a5591f909e79
			defaultHierarchy: LocalDateTable_ee3526ee-da87-43a3-9623-ea116ee21fd1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsCritical
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 605a3d45-f47b-4118-9548-987ba51f5496
		summarizeBy: none
		sourceColumn: IsCritical

		annotation SummarizationSetBy = Automatic

	partition dim_equipment_cleaned = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\JUNIOR USIU\Summer 2025\Data Viz\Final project\powerbi-capstone-Automotive-parts-02\Data\cleaned\dim_equipment_cleaned.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"InstallationDate", type date}, {"IsCritical", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

