table dim_time_cleaned
	lineageTag: 62be38e1-debb-4c8b-8acc-57dbb55d09c5

	column TimeID
		dataType: int64
		formatString: 0
		lineageTag: 07a69742-bbe1-4d2e-9c10-58b173d2f3db
		summarizeBy: none
		sourceColumn: TimeID

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: dateTime
		formatString: Long Date
		lineageTag: 03f234c5-203a-4808-94e6-fe0840f43899
		summarizeBy: none
		sourceColumn: Timestamp

		variation Variation
			isDefault
			relationship: 9360e57a-33a5-48f8-96e1-9d896c6b7dfa
			defaultHierarchy: LocalDateTable_32541905-2131-42e4-b9d3-df2b381f0a58.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Hour
		dataType: int64
		formatString: 0
		lineageTag: aebecd77-73d4-4e9a-b839-6a8d721655be
		summarizeBy: sum
		sourceColumn: Hour

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 6c53ad0b-6c0f-4aa5-b269-9d8edc3f859b
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 35bcd49e-f432-4f7f-8d61-da6af2359c3f
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: f2b10ca1-259d-4e29-8ecf-dca0df86671a
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: string
		lineageTag: 4d8c8adc-64fe-4403-aa73-9b01b28b6e6b
		summarizeBy: none
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	partition dim_time_cleaned = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\JUNIOR USIU\Summer 2025\Data Viz\Final project\PowerBi capstone\Data\cleaned\dim_time_cleaned.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"TimeID", Int64.Type}, {"Timestamp", type date}, {"Hour", Int64.Type}, {"Day", Int64.Type}, {"Month", Int64.Type}, {"Year", Int64.Type}, {"Weekday", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

