table dim_time_cleaned
	lineageTag: e376ce01-b222-4339-ac6e-28b276d93b26

	column TimeID
		dataType: string
		lineageTag: dfa7c36f-f08f-45eb-8296-e256e574aa1d
		summarizeBy: none
		sourceColumn: TimeID

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: string
		lineageTag: a8445bea-09d4-4742-97e6-6c65de9aec43
		summarizeBy: none
		sourceColumn: Timestamp

		annotation SummarizationSetBy = Automatic

	column Hour
		dataType: string
		lineageTag: 98da4348-ed09-4277-bb77-ecfeb1f0fd3c
		summarizeBy: none
		sourceColumn: Hour

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: string
		lineageTag: 8397624f-e643-43f9-8467-bbcca915c761
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 3d898a6b-9505-4991-a6cc-0c782df8c927
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: c703d140-377b-4b4d-8848-27b102376c36
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: string
		lineageTag: 173f5c31-8883-4d60-b497-78efc62ae6ae
		summarizeBy: none
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	partition dim_time_cleaned = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\user\Downloads\DSA 3050A\GROUP PROJECT\powerbi-capstone-Automotive-parts-02\Data\cleaned\dim_time_cleaned.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

