table dim_time_cleaned
	lineageTag: e376ce01-b222-4339-ac6e-28b276d93b26

	column TimeID
		dataType: string
		lineageTag: dfa7c36f-f08f-45eb-8296-e256e574aa1d
		summarizeBy: none
		sourceColumn: TimeID

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: dateTime
		formatString: Long Date
		lineageTag: a8445bea-09d4-4742-97e6-6c65de9aec43
		summarizeBy: none
		sourceColumn: Timestamp

		variation Variation
			isDefault
			relationship: 54a29ae9-d3df-4951-b868-fe92934d9e36
			defaultHierarchy: LocalDateTable_5c375684-f975-4840-875e-4d61c3b5eb13.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Hour
		dataType: int64
		formatString: 0
		lineageTag: 98da4348-ed09-4277-bb77-ecfeb1f0fd3c
		summarizeBy: sum
		sourceColumn: Hour

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: string
		lineageTag: 8397624f-e643-43f9-8467-bbcca915c761
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 3d898a6b-9505-4991-a6cc-0c782df8c927
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: c703d140-377b-4b4d-8848-27b102376c36
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Weekday
		dataType: string
		lineageTag: 173f5c31-8883-4d60-b497-78efc62ae6ae
		summarizeBy: none
		sourceColumn: Weekday

		annotation SummarizationSetBy = Automatic

	partition dim_time_cleaned = m
		mode: import
		source =
				let
<<<<<<< HEAD
				    Source = Csv.Document(File.Contents("D:\JUNIOR USIU\Summer 2025\Data Viz\Final project\powerbi-capstone-Automotive-parts-02\Data\cleaned\dim_time_cleaned.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
=======
				    Source = Csv.Document(File.Contents("C:\Users\jkaru\VSCODE PYTHON PROJECTS\powerbi-capstone-Automotive-parts-02\Data\cleaned\dim_time_cleaned.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
>>>>>>> 765dc9742845f51fc65c90ebfd4c90aa0d80c1aa
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Timestamp", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

