table dim_sensor_cleaned
	lineageTag: 2c9a493f-5926-4ff4-a564-16b36e4899c9

	column SensorID
		dataType: string
		lineageTag: 72ceb8a1-c8fe-47a0-8f9f-7729a601ba1a
		summarizeBy: none
		sourceColumn: SensorID

		annotation SummarizationSetBy = Automatic

	column SensorType
		dataType: string
		lineageTag: 217ec999-e40e-47a0-acd3-b46df8e6bcc2
		summarizeBy: none
		sourceColumn: SensorType

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 4edff316-d9d2-40e2-86a9-ab471c720bd4
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column CalibrationDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4a2a17ff-6e5b-4bec-af99-d674ea80dde2
		summarizeBy: none
		sourceColumn: CalibrationDate

		variation Variation
			isDefault
			relationship: 08752d66-0a88-492e-95f6-e911afaf84c6
			defaultHierarchy: LocalDateTable_639b5fce-43b0-4959-92cd-f937c68453bf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_sensor_cleaned = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jkaru\powerbi-capstone-Automotive-parts-02\Data\cleaned\dim_sensor_cleaned.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SensorID", type text}, {"SensorType", type text}, {"Unit", type text}, {"CalibrationDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

