table dim_equipment_cleaned
	lineageTag: 91217463-8038-42a9-9e24-a8089538f615

	measure CriticalEquip_LowHealthCount =
			
			CALCULATE(
			    COUNTROWS(fact_table_cleaned),
			    FILTER(
			        fact_table_cleaned,
			        fact_table_cleaned[HealthScore] < 50 &&
			        RELATED(dim_equipment_cleaned[IsCritical]) = TRUE()
			    )
			)
		formatString: 0
		lineageTag: c19d0d05-dc5d-438f-bc0a-6a3518762290

	measure 'Reactive-to-Preventive Cost Ratio' =
			
			DIVIDE(SUM(fact_table_cleaned[ReactiveCost]), SUM(fact_table_cleaned[PreventiveCost]))
		lineageTag: 1ae946fe-4401-4dd8-9916-27de2098a077

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Equipment_Count = DISTINCTCOUNT(dim_equipment_cleaned[EquipmentID])
		formatString: 0
		lineageTag: f7bd1c21-28ac-4311-bfeb-bf8a04ebcf69

	measure Count_CriticalEquipment =
			
			CALCULATE(
			    COUNTROWS(dim_equipment_cleaned),
			    FILTER(
			        dim_equipment_cleaned,
			        dim_equipment_cleaned[IsCritical] = "True"
			    )
			)
		formatString: 0
		lineageTag: 6d1c2445-eca6-43d4-aea8-cb5c46938f0d

	column EquipmentID
		dataType: string
		lineageTag: de4a73b2-ecbd-4796-bc52-a74c423e28b2
		summarizeBy: none
		sourceColumn: EquipmentID

		annotation SummarizationSetBy = Automatic

	column EquipmentType
		dataType: string
		lineageTag: 16409b37-f651-4ca0-b6a1-6979daaeefbf
		summarizeBy: none
		sourceColumn: EquipmentType

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		lineageTag: cf11e3a9-df88-47ea-a83f-0b4c262f4cb4
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	column InstallationDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 774136bf-35c3-4e70-a09d-00e4c0bd9ebb
		summarizeBy: none
		sourceColumn: InstallationDate

		variation Variation
			isDefault
			relationship: 984917ec-1474-4a49-9e02-a5591f909e79
			defaultHierarchy: LocalDateTable_ee3526ee-da87-43a3-9623-ea116ee21fd1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IsCritical
<<<<<<< HEAD
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 605a3d45-f47b-4118-9548-987ba51f5496
=======
		dataType: string
		lineageTag: 39a87cdc-9b5e-4a08-9907-052e91fc5463
>>>>>>> 2c1f8934cc14d265123955f1eff18500f4388fcd
		summarizeBy: none
		sourceColumn: IsCritical

		annotation SummarizationSetBy = Automatic

	partition dim_equipment_cleaned = m
		mode: import
		source =
				let
<<<<<<< HEAD
				    Source = Csv.Document(File.Contents("C:\Users\user\Downloads\DSA 3050A\GROUP PROJECT\powerbi-capstone-Automotive-parts-02\Data\cleaned\dim_equipment_cleaned.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"InstallationDate", type date}, {"IsCritical", type logical}})
=======
				    Source = Csv.Document(File.Contents("D:\JUNIOR USIU\Summer 2025\Data Viz\Final project\PowerBi capstone\Data\cleaned\dim_equipment_cleaned.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EquipmentID", type text}, {"EquipmentType", type text}, {"Manufacturer", type text}, {"InstallationDate", type date}, {"IsCritical", type text}})
>>>>>>> 2c1f8934cc14d265123955f1eff18500f4388fcd
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

