table dim_locatiion_cleaned
	lineageTag: ef6b6b94-e4da-4d0e-ac81-3c67d1a1bae1

	column LocationID
		dataType: string
		lineageTag: 88f49de1-b75c-4ea4-a6c6-6451ab80a313
		summarizeBy: none
		sourceColumn: LocationID

		annotation SummarizationSetBy = Automatic

	column LocationName
		dataType: string
		lineageTag: d5ad10ec-458e-428b-b3aa-60196bddedad
		summarizeBy: none
		sourceColumn: LocationName

		annotation SummarizationSetBy = Automatic

	column ProductionLine
		dataType: string
		lineageTag: af7e7cc5-e084-4923-8872-40127e08459d
		summarizeBy: none
		sourceColumn: ProductionLine

		annotation SummarizationSetBy = Automatic

	partition dim_locatiion_cleaned = m
		mode: import
		source =
				let
<<<<<<< HEAD
				    Source = Csv.Document(File.Contents("D:\JUNIOR USIU\Summer 2025\Data Viz\Final project\powerbi-capstone-Automotive-parts-02\Data\cleaned\dim_locatiion_cleaned.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
=======
				    Source = Csv.Document(File.Contents("C:\Users\jkaru\VSCODE PYTHON PROJECTS\powerbi-capstone-Automotive-parts-02\Data\cleaned\dim_locatiion_cleaned.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
>>>>>>> 765dc9742845f51fc65c90ebfd4c90aa0d80c1aa
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

