table dim_locatiion_cleaned
	lineageTag: 4a23838f-e026-43ca-aa31-1a64839381f7

	column LocationID
		dataType: string
		lineageTag: 0f6f3c56-e971-425f-8d29-30c5a468b5fd
		summarizeBy: none
		sourceColumn: LocationID

		annotation SummarizationSetBy = Automatic

	column LocationName
		dataType: string
		lineageTag: 2d2f4f1e-a807-4da1-bc2c-f815c2ba1d3d
		summarizeBy: none
		sourceColumn: LocationName

		annotation SummarizationSetBy = Automatic

	column ProductionLine
		dataType: string
		lineageTag: 75ccf4a6-e61f-400c-9778-1eb0496721f3
		summarizeBy: none
		sourceColumn: ProductionLine

		annotation SummarizationSetBy = Automatic

	partition dim_locatiion_cleaned = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\jkaru\powerbi-capstone-Automotive-parts-02\Data\cleaned\dim_locatiion_cleaned.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"LocationID", type text}, {"LocationName", type text}, {"ProductionLine", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

