table dim_locatiion_cleaned
	lineageTag: ef6b6b94-e4da-4d0e-ac81-3c67d1a1bae1

	column LocationID
		dataType: string
		lineageTag: 88f49de1-b75c-4ea4-a6c6-6451ab80a313
		summarizeBy: none
		sourceColumn: LocationID

		annotation SummarizationSetBy = Automatic

	column LocationName
		dataType: string
		lineageTag: d5ad10ec-458e-428b-b3aa-60196bddedad
		summarizeBy: none
		sourceColumn: LocationName

		annotation SummarizationSetBy = Automatic

	column ProductionLine
		dataType: string
		lineageTag: af7e7cc5-e084-4923-8872-40127e08459d
		summarizeBy: none
		sourceColumn: ProductionLine

		annotation SummarizationSetBy = Automatic

	partition dim_locatiion_cleaned = m
		mode: import
		source =
				let
<<<<<<< HEAD
				    Source = Csv.Document(File.Contents("C:\Users\user\Downloads\DSA 3050A\GROUP PROJECT\powerbi-capstone-Automotive-parts-02\Data\cleaned\dim_locatiion_cleaned.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
=======
				    Source = Csv.Document(File.Contents("D:\JUNIOR USIU\Summer 2025\Data Viz\Final project\PowerBi capstone\Data\cleaned\dim_locatiion_cleaned.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"LocationID", type text}, {"LocationName", type text}, {"ProductionLine", type text}})
>>>>>>> 2c1f8934cc14d265123955f1eff18500f4388fcd
				in
				    #"Promoted Headers"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

