table fact_table_cleaned
	lineageTag: dd6ad3d9-a11a-45e6-9ad7-1725108f2b2c

	column SensorDataID
		dataType: string
		lineageTag: 2c964c14-2b6a-4647-a771-cc523db0de0c
		summarizeBy: none
		sourceColumn: SensorDataID

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: dateTime
		formatString: Long Date
		lineageTag: f34a846c-7465-460c-bb58-5b42944a36f5
		summarizeBy: none
		sourceColumn: Timestamp

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EquipmentID
		dataType: string
		lineageTag: 272ba7a1-e5f1-4abe-8569-dc1bbc20cd69
		summarizeBy: none
		sourceColumn: EquipmentID

		annotation SummarizationSetBy = Automatic

	column TimeID
		dataType: string
		lineageTag: 030bac3d-29cb-40fe-b6af-18c9cd4e0b1d
		summarizeBy: none
		sourceColumn: TimeID

		annotation SummarizationSetBy = Automatic

	column SensorID
		dataType: string
		lineageTag: 790d1ad1-1e7e-4752-bb32-2903d200dc76
		summarizeBy: none
		sourceColumn: SensorID

		annotation SummarizationSetBy = Automatic

	column LocationID
		dataType: string
		lineageTag: c47167fa-8dac-4da2-9bb8-d1b18c70f29d
		summarizeBy: none
		sourceColumn: LocationID

		annotation SummarizationSetBy = Automatic

	column Temperature
		dataType: double
		lineageTag: 85a98420-2bff-4895-8aeb-b65366ea94af
		summarizeBy: sum
		sourceColumn: Temperature

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Vibration
		dataType: double
		lineageTag: 66160c14-1a05-4c4f-9ed3-51f39249d0ea
		summarizeBy: sum
		sourceColumn: Vibration

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Pressure
		dataType: double
		lineageTag: 6d5b39a4-53a3-489e-a8eb-d44ec61f7c55
		summarizeBy: sum
		sourceColumn: Pressure

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Voltage
		dataType: double
		lineageTag: e7dc19f1-d085-452b-8b5c-43bbeb9d5b1f
		summarizeBy: sum
		sourceColumn: Voltage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TempNorm
		dataType: double
		lineageTag: 91c8e9b9-ff73-46b5-9b77-5c9b9e5c3eff
		summarizeBy: sum
		sourceColumn: TempNorm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VibNorm
		dataType: double
		lineageTag: 39c5953b-c19b-497b-a02a-420fa082618c
		summarizeBy: sum
		sourceColumn: VibNorm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VoltNorm
		dataType: double
		lineageTag: 71df9dc1-3585-48f6-a0b5-845dda983d55
		summarizeBy: sum
		sourceColumn: VoltNorm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PresNorm
		dataType: double
		lineageTag: e3d5dc7e-b4ea-40cc-9548-6a5973676886
		summarizeBy: sum
		sourceColumn: PresNorm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HealthScore
		dataType: double
		lineageTag: 117e48c4-937f-4dd7-884e-6cd49e0e35ae
		summarizeBy: sum
		sourceColumn: HealthScore

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PredictedFailure
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 08d84f68-57fe-4e02-88cd-061931627a71
		summarizeBy: none
		sourceColumn: PredictedFailure

		annotation SummarizationSetBy = Automatic

	column ReactiveCost
		dataType: int64
		formatString: 0
		lineageTag: 8e69cca0-b5fb-4a83-beeb-cec891dd7ca5
		summarizeBy: sum
		sourceColumn: ReactiveCost

		annotation SummarizationSetBy = Automatic

	column PreventiveCost
		dataType: int64
		formatString: 0
		lineageTag: 31994d8c-a14f-4beb-b75d-3c67ebbc9777
		summarizeBy: sum
		sourceColumn: PreventiveCost

		annotation SummarizationSetBy = Automatic

	column CostAvoided
		dataType: int64
		formatString: 0
		lineageTag: 3b07f227-1fe6-4623-9dc7-c3df3be77183
		summarizeBy: sum
		sourceColumn: CostAvoided

		annotation SummarizationSetBy = Automatic

	partition fact_table_cleaned = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\user\Downloads\DSA 3050A\GROUP PROJECT\powerbi-capstone-Automotive-parts-02\Data\cleaned\fact_table_cleaned.csv"),[Delimiter=",", Columns=19, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Timestamp", type date}, {"Temperature", type number}, {"Vibration", type number}, {"Pressure", type number}, {"Voltage", type number}, {"TempNorm", type number}, {"VibNorm", type number}, {"VoltNorm", type number}, {"PresNorm", type number}, {"HealthScore", type number}, {"ReactiveCost", Int64.Type}, {"PreventiveCost", Int64.Type}, {"CostAvoided", Int64.Type}, {"PredictedFailure", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

