table fact_table_cleaned
	lineageTag: 612ca46d-3e5c-4e3a-9b09-a71724891eb4

	measure 'Total Cost Avoided' = ```
			SUM(fact_table_cleaned[CostAvoided])
			
			```
		formatString: 0
		lineageTag: 92ce5aef-8c73-4191-8681-b7f6ece14fe4

	measure 'Total Preventive Cost' = SUM(fact_table_cleaned[PreventiveCost])
		formatString: 0
		lineageTag: 07a97a78-b582-4f04-9eb6-e8f38cc30f4f

	measure 'Total Reactive Cost' = SUM(fact_table_cleaned[ReactiveCost])
		formatString: 0
		lineageTag: a39a6289-a67d-479b-8053-07c76e69070d

	measure 'Average Health Score' = AVERAGE(fact_table_cleaned[HealthScore])
		lineageTag: 6662fda4-b4e4-482d-be56-bdf6f7136de7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Temperature' = AVERAGE(fact_table_cleaned[Temperature])
		lineageTag: c8eb75bf-2137-4f92-b820-076f951c0bdb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Vibration' = AVERAGE(fact_table_cleaned[Vibration])
		lineageTag: aa71379c-04cd-4e8c-acb7-87e8032ca6a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Pressure' = AVERAGE(fact_table_cleaned[Pressure])
		lineageTag: cc17dc0c-6edf-4215-95eb-d48390b8febf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Voltage'
		lineageTag: 60e36461-c144-44a4-ae2f-c8e4a9a92921

	measure 'Failure Count' = COUNTROWS(FILTER(fact_table_cleaned, fact_table_cleaned[PredictedFailure] = TRUE()))
		formatString: 0
		lineageTag: 45770ad8-044a-463f-aefd-b70f3e5bb676

	measure 'Average Health Score (Failed Equipment)' =
			
			CALCULATE(
			    AVERAGE(fact_table_cleaned[HealthScore]),
			    fact_table_cleaned[PredictedFailure] = TRUE()
			)
		lineageTag: dcc4db0f-cdd6-4924-888a-25ca4a13d712

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Maximum Temperature' = MAX(fact_table_cleaned[Temperature])
		lineageTag: 20eb5228-373d-4f77-9cf4-110dbe74d228

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% of equipments likely to fail' =
			DIVIDE(
			    CALCULATE(
			        COUNTROWS(fact_table_cleaned),
			        FILTER(
			            fact_table_cleaned,
			            fact_table_cleaned[PredictedFailure] = "True"
			        )
			    ),
			    COUNTROWS(fact_table_cleaned)
			)
		formatString: 0
		lineageTag: 2340137d-4271-41ad-8719-0f213a7ee4f4

	measure CriticalEquip_HighVibration =
			
			CALCULATE(
			    COUNTROWS(fact_table_cleaned),
			    FILTER(
			        fact_table_cleaned,
			        fact_table_cleaned[Vibration] > 5 &&
			        RELATED(dim_equipment_cleaned[IsCritical]) = TRUE()
			    )
			)
		formatString: 0
		lineageTag: 6efda32d-8df4-48be-9495-69c09ec1e6d8

	column SensorDataID
		dataType: string
		lineageTag: 684f5815-de86-477f-bdc8-953c1e53873e
		summarizeBy: none
		sourceColumn: SensorDataID

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 748dff5a-9e19-4ed0-871a-1e02eac1a475
		summarizeBy: none
		sourceColumn: Timestamp

		variation Variation
			isDefault
			relationship: 3f95b29e-83db-45b2-ac0a-6e33ba4fa0fc
			defaultHierarchy: LocalDateTable_171a2de4-9a50-4c2f-aa54-85b9d100ac06.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column EquipmentID
		dataType: string
		lineageTag: 55cca41e-7506-4619-9c3a-115f03461266
		summarizeBy: none
		sourceColumn: EquipmentID

		annotation SummarizationSetBy = Automatic

	column TimeID
		dataType: string
		lineageTag: 41c18230-78a8-4ac7-b75c-6e59f194eeae
		summarizeBy: none
		sourceColumn: TimeID

		annotation SummarizationSetBy = Automatic

	column SensorID
		dataType: string
		lineageTag: 147d4534-98a7-4519-baeb-36aafaa18934
		summarizeBy: none
		sourceColumn: SensorID

		annotation SummarizationSetBy = Automatic

	column LocationID
		dataType: string
		lineageTag: 1ab13b74-8d40-4572-a2d6-ee725be38c92
		summarizeBy: none
		sourceColumn: LocationID

		annotation SummarizationSetBy = Automatic

	column Temperature
		dataType: double
		lineageTag: 962d100d-a50e-442c-9ce9-f1c514b494b6
		summarizeBy: sum
		sourceColumn: Temperature

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Vibration
		dataType: double
		lineageTag: a68b209c-6f67-43b9-882d-d5047ed742e4
		summarizeBy: sum
		sourceColumn: Vibration

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Pressure
		dataType: double
		lineageTag: 123e9a8f-688d-49b1-99eb-4e1ee4237214
		summarizeBy: sum
		sourceColumn: Pressure

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Voltage
		dataType: double
		lineageTag: bf6d651c-9c85-4605-b3ac-411bfc17deb7
		summarizeBy: sum
		sourceColumn: Voltage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TempNorm
		dataType: double
		lineageTag: 1d768325-980a-4364-9d4e-6faebef30968
		summarizeBy: sum
		sourceColumn: TempNorm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VibNorm
		dataType: double
		lineageTag: c632eec5-12cf-4eea-ac76-8cd6d86adf16
		summarizeBy: sum
		sourceColumn: VibNorm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VoltNorm
		dataType: double
		lineageTag: c71a122e-052d-4740-853c-bda79b74cde6
		summarizeBy: sum
		sourceColumn: VoltNorm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PresNorm
		dataType: double
		lineageTag: dc2ff27e-513d-4e4d-9f96-6802dd2f9705
		summarizeBy: sum
		sourceColumn: PresNorm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HealthScore
		dataType: double
		lineageTag: 252e5558-7f82-4766-9995-4895c10b5ce5
		summarizeBy: sum
		sourceColumn: HealthScore

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PredictedFailure
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bfde9364-8d3e-485e-b368-7ac649ea8170
		summarizeBy: none
		sourceColumn: PredictedFailure

		annotation SummarizationSetBy = Automatic

	column ReactiveCost
		dataType: int64
		formatString: 0
		lineageTag: 66375c9b-9023-4ac3-9e1b-59474bb8e8eb
		summarizeBy: sum
		sourceColumn: ReactiveCost

		annotation SummarizationSetBy = Automatic

	column PreventiveCost
		dataType: int64
		formatString: 0
		lineageTag: 1988c2c3-79e9-48ff-b770-d2e4b43680f6
		summarizeBy: sum
		sourceColumn: PreventiveCost

		annotation SummarizationSetBy = Automatic

	column CostAvoided
		dataType: int64
		formatString: 0
		lineageTag: e0fe1f3c-8e3a-4032-b681-e5c3de1eb8e7
		summarizeBy: sum
		sourceColumn: CostAvoided

		annotation SummarizationSetBy = Automatic

	partition fact_table_cleaned = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\JUNIOR USIU\Summer 2025\Data Viz\Final project\PowerBi capstone\Data\cleaned\fact_table_cleaned.csv"),[Delimiter=",", Columns=19, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SensorDataID", type text}, {"Timestamp", type date}, {"EquipmentID", type text}, {"TimeID", type text}, {"SensorID", type text}, {"LocationID", type text}, {"Temperature", type number}, {"Vibration", type number}, {"Pressure", type number}, {"Voltage", type number}, {"TempNorm", type number}, {"VibNorm", type number}, {"VoltNorm", type number}, {"PresNorm", type number}, {"HealthScore", type number}, {"PredictedFailure", type logical}, {"ReactiveCost", Int64.Type}, {"PreventiveCost", Int64.Type}, {"CostAvoided", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

